  server {
      listen 8080;
 
      location /services/oauth2/ {
          proxy_pass https://login.salesforce.com/services/oauth2/;
          proxy_set_header Host login.salesforce.com;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_ssl_server_name on;
      }
 
      # Serve the React SPA
      location / {
          root /usr/share/nginx/html;
          index index.html;
          try_files $uri $uri/ /index.html;
      }
  }
